"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import FlowMark from "@/components/FlowMark";
import ThemeToggle from "@/components/ThemeToggle";
import FlowShareCard from "@/components/FlowShareCard";

type Token={address:string;name:string;symbol:string;image:string|null;priceUsd:string|null;liquidityUsd:number;volume1h:number;volume24h:number;change1h:number;change24h:number;buys5m:number;sells5m:number;buys1h:number;sells1h:number;buys24h:number;sells24h:number;marketCap:number|null;promoted:boolean;createdAt?:number|null;holders?:number|null;mintAuthority?:string|null;freezeAuthority?:string|null};
const money=(n:number)=>n>=1e9?"$"+(n/1e9).toFixed(1)+"B":n>=1e6?"$"+(n/1e6).toFixed(1)+"M":n>=1e3?"$"+(n/1e3).toFixed(1)+"K":"$"+n.toFixed(0);
const price=(v:string|null)=>{if(!v)return "—";const n=Number(v);return !Number.isFinite(n)?"—":n>=1?"$"+n.toFixed(2):n>=.01?"$"+n.toFixed(4):"$"+n.toPrecision(4)};
function Spark({points}:{points:number[]}){if(points.length<2)return <span className="text-[8px] text-[var(--muted)]">history pending</span>;const min=Math.min(...points),max=Math.max(...points),span=max-min||1;const p=points.map((v,i)=>((i/(points.length-1))*100).toFixed(1)+","+((91-((v-min)/span)*78)).toFixed(1)).join(" ");return <svg viewBox="0 0 100 100" className="h-8 w-24" preserveAspectRatio="none"><polyline fill="none" stroke="currentColor" strokeWidth="3" points={p}/></svg>}

export default function Home(){
 const [tokens,setTokens]=useState<Token[]>([]);const [sparks,setSparks]=useState<Record<string,number[]>>({});const [selected,setSelected]=useState<Token|null>(null);
 async function load(){try{const r=await fetch("/api/discovery",{cache:"no-store"});const d=await r.json();const next=(d.tokens||[]).slice(0,3) as Token[];setTokens(next);const rows=await Promise.all(next.map(async t=>{try{const r=await fetch("/api/token-events?address="+encodeURIComponent(t.address)+"&symbol="+encodeURIComponent(t.symbol),{cache:"no-store"});const d=await r.json();return [t.address,(d.snapshots||[]).map((x:any)=>x.priceUsd).filter((x:any)=>typeof x==="number")] as const}catch{return [t.address,[]] as const}}));setSparks(Object.fromEntries(rows))}catch{}}
 useEffect(()=>{void load();const id=window.setInterval(load,30000);return()=>window.clearInterval(id)},[]);
 return <main className="min-h-screen bg-[var(--bg)] text-[var(--fg)]">
  <header className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 md:px-8"><Link href="/" className="flex items-center gap-3"><FlowMark compact/><span className="font-semibold tracking-[-.04em]">FLOW</span></Link><nav className="hidden items-center gap-7 text-sm text-[var(--muted)] md:flex"><Link href="/discover">Discover</Link><Link href="/autopilot">Autopilot</Link><Link href="/watch">Watch</Link></nav><div className="flex items-center gap-2"><ThemeToggle/><Link href="/connect/fund" className="rounded-full border border-[var(--line-strong)] px-4 py-2 text-xs font-semibold">Connect wallet</Link></div></header>

  <section className="relative overflow-hidden border-t border-[var(--line)]"><div className="hero-art" aria-hidden="true"><div className="hero-flow"/></div><div className="relative mx-auto max-w-7xl px-5 pb-24 pt-20 md:px-8 md:pb-32 md:pt-28"><div className="max-w-5xl"><div className="mono text-[9px] uppercase tracking-[.2em] text-[var(--accent)]">Solana market intelligence</div><h1 className="mt-6 text-6xl font-semibold leading-[.9] tracking-[-.07em] md:text-9xl">Every move<br/><span className="text-[var(--accent)]">has a reason.</span></h1><p className="mt-8 max-w-2xl text-base leading-7 text-[var(--muted)] md:text-lg">FLOW shows why Solana tokens are moving, from volume changes and buy flow to wallet activity, liquidity and social signals. Read the evidence before you decide what to do.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/discover" className="rounded-full bg-[var(--fg)] px-7 py-4 text-center text-sm font-bold text-[var(--bg)]">Explore markets</Link><Link href="/autopilot" className="px-7 py-4 text-center text-sm font-semibold underline underline-offset-4">See how Autopilot works →</Link></div><div className="mt-5 text-[10px] text-[var(--muted)]">No wallet needed to explore.</div></div></div></section>

  <section className="border-y border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-5 md:px-8"><div className="flex items-center justify-between"><div className="mono text-[8px] tracking-[.18em] text-[var(--muted)]">LIVE / WHAT'S MOVING</div><div className="mono text-[8px] text-[var(--muted)]">LIVE MARKET FEED</div></div><div className="mt-5 grid divide-y border-y border-[var(--line)] md:grid-cols-3 md:divide-x md:divide-y-0">{tokens.map(t=><div key={t.address} className="p-5"><div className="flex items-start justify-between gap-4"><div><div className="text-sm font-semibold">{"$"+t.symbol}</div><div className="mt-1 text-[10px] text-[var(--muted)]">{price(t.priceUsd)} · {t.change1h>=0?"+":""}{t.change1h.toFixed(1)}% 1H</div></div><Spark points={sparks[t.address]||[]}/></div><div className="mt-5 flex items-center justify-between"><span className="text-[9px] text-[var(--muted)]">Liquidity {money(t.liquidityUsd)}</span><button onClick={()=>setSelected(t)} className="rounded-full border border-[var(--line-strong)] px-3 py-1.5 text-[9px] font-semibold">Why?</button></div></div>)}{!tokens.length&&<div className="p-8 text-sm text-[var(--muted)] md:col-span-3">Waiting for live market data. No placeholder tokens are shown.</div>}</div></div></section>

  <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:grid-cols-[.8fr_1.2fr] md:px-8 md:py-28"><div><div className="mono text-[9px] tracking-[.18em] text-[var(--accent)]">WHY IT'S MOVING</div><h2 className="mt-5 text-5xl font-semibold tracking-[-.06em] md:text-7xl">Don&apos;t just watch price. <span className="text-[var(--muted)]">Read it.</span></h2></div><div><p className="max-w-xl text-base leading-7 text-[var(--muted)]">Open any token and see the price, the flow behind it, and a timeline of observed events. FLOW separates timestamped evidence from claims of causality.</p><div className="mt-10 rounded-3xl border border-[var(--line)] p-6"><div className="mono text-[8px] text-[var(--muted)]">EVIDENCE TIMELINE</div><div className="mt-6 space-y-5"><div className="flex gap-4"><span className="mono text-[8px] text-[var(--muted)]">01</span><span className="text-sm">Market conditions change.</span></div><div className="flex gap-4"><span className="mono text-[8px] text-[var(--muted)]">02</span><span className="text-sm">Observed events are timestamped.</span></div><div className="flex gap-4"><span className="mono text-[8px] text-[var(--muted)]">03</span><span className="text-sm">The timeline shows evidence, not invented causality.</span></div></div></div></div></section>

  <section className="border-y border-[var(--line)]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:grid-cols-2 md:px-8 md:py-24"><div><div className="mono text-[9px] tracking-[.18em] text-[var(--accent)]">FLOW SCORE</div><h2 className="mt-5 text-5xl font-semibold tracking-[-.06em]">One number.<br/>Fully explained.</h2><p className="mt-6 max-w-lg text-sm leading-6 text-[var(--muted)]">Rates a token's market health from 0 to 100. It doesn&apos;t predict price.</p><Link href="/score" className="mt-7 inline-flex rounded-full border border-[var(--line-strong)] px-5 py-3 text-xs font-semibold">How the score works →</Link></div><div className="rounded-3xl border border-[var(--line)] bg-[var(--panel)] p-6"><div className="mono text-[9px] text-[var(--muted)]">BANDS</div><div className="mt-7 space-y-3"><div className="rounded-2xl border border-[var(--line)] p-4"><b className="text-emerald-500">80–100 · Healthy</b></div><div className="rounded-2xl border border-[var(--line)] p-4"><b className="text-amber-500">50–79 · Mixed</b></div><div className="rounded-2xl border border-[var(--line)] p-4"><b className="text-red-500">0–49 · Fragile</b></div></div></div></div></section>

  <section className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-24"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="mono text-[9px] tracking-[.18em] text-[var(--accent)]">SHARE CARDS</div><h2 className="mt-4 text-5xl font-semibold tracking-[-.06em]">Post the proof.</h2></div><p className="max-w-md text-sm leading-6 text-[var(--muted)]">The move, the causes, the score and confidence — in one shareable card.</p></div><div className="mt-10 max-w-xl">{selected?<FlowShareCard token={selected}/>:tokens[0]?<FlowShareCard token={tokens[0]}/>:<div className="rounded-3xl border border-[var(--line)] p-8 text-sm text-[var(--muted)]">A live token is required before a share card can be generated.</div>}</div></section>

  <section className="border-y border-[var(--line)]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:grid-cols-2 md:px-8 md:py-24"><div><div className="mono text-[9px] tracking-[.18em] text-[var(--accent)]">WATCH</div><h2 className="mt-5 text-5xl font-semibold tracking-[-.06em]">Build your radar.</h2></div><div><p className="max-w-xl text-base leading-7 text-[var(--muted)]">Keep the markets you care about close, with alerts when flow changes. No wallet required.</p><Link href="/watch" className="mt-7 inline-flex rounded-full bg-[var(--fg)] px-6 py-3 text-xs font-bold text-[var(--bg)]">Open Watch →</Link></div></div></section>

  <section className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-24"><div className="max-w-3xl"><div className="mono text-[9px] tracking-[.18em] text-[var(--accent)]">AUTOPILOT</div><h2 className="mt-5 text-5xl font-semibold tracking-[-.06em] md:text-7xl">Your rules. Your trades. Your off switch.</h2><p className="mt-6 text-base leading-7 text-[var(--muted)]">Autopilot buys and sells only inside the limits you set.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[["01","Set the guardrails.","Spend per trade, daily cap, stop-loss and other execution limits."],["02","Rehearse with paper money.","Observe the rules before using live funds."],["03","Every trade shows its work.","See the signals and limits behind each live execution."]].map(([n,h,b])=><div key={n} className="rounded-3xl border border-[var(--line)] p-6"><div className="mono text-[9px] text-[var(--muted)]">{n}</div><h3 className="mt-8 font-semibold">{h}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{b}</p></div>)}</div><div className="mt-6 rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-5 text-sm text-[var(--muted)]"><b className="text-[var(--fg)]">Paper performance:</b> no verified 7-day result is published until a real paper-trading ledger supplies the number. You can lose everything you trade. Autopilot follows rules; it does not predict.</div><Link href="/autopilot" className="mt-7 inline-flex rounded-full border border-[var(--line-strong)] px-5 py-3 text-xs font-semibold">Try paper Autopilot →</Link></section>

  <section className="border-y border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-24"><div className="mono text-[9px] tracking-[.18em] text-[var(--accent)]">TRUST</div><h2 className="mt-5 text-5xl font-semibold tracking-[-.06em]">Built to be checked.</h2><div className="mt-10 grid gap-px overflow-hidden rounded-3xl border border-[var(--line)] bg-[var(--line)] md:grid-cols-4">{[["NON-CUSTODIAL","Your keys stay yours."],["DATA","DexScreener powers the public discovery feed. Other sources are identified where used."],["MISSING DATA","Missing is shown as missing, never silently guessed."],["FORMULA","Score changes are logged publicly."]].map(([a,b])=><div key={a} className="bg-[var(--bg)] p-6"><div className="mono text-[8px] text-[var(--muted)]">{a}</div><p className="mt-5 text-sm leading-6">{b}</p></div>)}</div></div></section>

  <section className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-24"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><div className="mono text-[9px] tracking-[.18em] text-[var(--accent)]">WALLET</div><h2 className="mt-5 text-5xl font-semibold tracking-[-.06em]">The wallet can wait.</h2><p className="mt-5 max-w-xl text-base leading-7 text-[var(--muted)]">Explore first. Connect only when you want to trade or run Autopilot.</p></div><Link href="/discover" className="rounded-full bg-[var(--fg)] px-6 py-3 text-center text-xs font-bold text-[var(--bg)]">Start exploring</Link></div></section>

  <section className="border-t border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-24"><div className="mono text-[9px] tracking-[.18em] text-[var(--accent)]">FAQ</div><div className="mt-8 grid gap-4 md:grid-cols-2">{[["Is it free?","Market discovery is available without connecting a wallet. Trading or Autopilot access may use separate product fees."],["Which wallets work?","The connect screen shows the wallets available in the current Solana Wallet Adapter build."],["Can I lose money?","Yes. Token trading is high risk, including loss of the funds traded."],["Where does the data come from?","The public discovery feed currently comes from DexScreener. Additional connected sources are disclosed next to the signals they power."]].map(([q,a])=><div key={q} className="rounded-2xl border border-[var(--line)] p-5"><b className="text-sm">{q}</b><p className="mt-2 text-sm text-[var(--muted)]">{a}</p></div>)}</div></div></section>

  <footer className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-10 text-[10px] text-[var(--muted)] md:px-8"><div className="flex flex-wrap items-center gap-5"><span>FLOW · SOLANA MARKET INTELLIGENCE</span><Link href="/score">Score methodology</Link><Link href="/changelog">Changelog</Link><Link href="/help">Docs</Link><span>X</span><span>Telegram</span></div><div>Market data is informational. Nothing here is a recommendation or guarantee.</div></footer>

  {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-5" onClick={()=>setSelected(null)}><div className="w-full max-w-xl" onClick={e=>e.stopPropagation()}><div className="mb-3 flex justify-end"><button onClick={()=>setSelected(null)} className="rounded-full border border-white/20 bg-black px-4 py-2 text-xs text-white">Close</button></div><FlowShareCard token={selected}/></div></div>}
 </main>;
}